version: '2.3'

services: 

    app:
        build: .
        container_name: app
        volumes: 
            - .:/var/www
        networks: 
            - my-network

    nginx:
        build: .docker/nginx
        container_name: nginx
        tty: true
        restart: always
        ports:
            - "8000:80"
        volumes:
            - .:/var/www   
        networks: 
            - my-network 

    redis:
        image: redis:alpine
        expose: 
            - 6379
        networks:
            - my-network

    db:
        build: .docker/database
        command: --innodb-use-native-aio=0 
        container_name: db
        tty: true
        restart: always
        volumes: 
            - ./.docker/dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks: 
            - my-network          

  
networks: 
    my-network: 
        driver: bridge
